version: '3'

services:
  zeppelin:
    image: 
    - apache/zeppelin:0.9.0
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      - ZEPPELIN_NOTEBOOK_DIR='/notebook'
      - ZEPPELIN_LOG_DIR='/logs'
    volumes:
      - $PWD/Zeppelin/logs:/logs
      - $PWD/Zeppelin/notebook:/notebook
      - $PWD/Zeppelin/interpretador:/zeppelin/interpreter/jdbc
      - /home/bosco:/zeppelin/bosco
    command:
      - bash /zeppelin/bin/zeppelin.sh
    privileged: true
  jupyter:
    image: 
    - jupyter/pyspark-notebook
    volumes:
    - $PWD/notebook:/home/jovyan/work
    ports:
    - "8888:8888"
